export const HandleClick = 'handleClick'
export const HandleClickMinimize = 'handleClickMinimize'
export const HandleClickToggleClose = 'handleClickToggleClose'
export const HandleClickToggleMaximize = 'handleClickToggleMaximize'
export const HandleFocusIn = 'handleFocusIn'
export const HandleFocusOut = 'handleFocusOut'
export const HandlePointerOut = 'handlePointerOut'
export const HandlePointerOver = 'handlePointerOver'
