# Based on https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml by BurntSushi (License MIT)

name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-24.04
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      rg_version: ${{ env.RG_VERSION }}
    steps:
      - name: Get the release version from the tag
        shell: bash
        if: env.RG_VERSION == ''
        run: |
          echo "RG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.RG_VERSION }}"
      - name: Create GitHub release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RG_VERSION }}
          release_name: ${{ env.RG_VERSION }}
          draft: true

  build-release:
    name: build-release
    needs: ['create-release']
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [windows-2022, macos-14, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - name: Compute node modules cache key
        id: nodeModulesCacheKey
        run: echo "value=$(node packages/build/src/computeNodeModulesCacheKey.js)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cacheNodeModules-${{ steps.nodeModulesCacheKey.outputs.value }}
      - name: npm ci
        run: npm ci --ignore-scripts && npm run postinstall
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npm run build
      - run: npm run build:static
      - run: npm test
      - run: npm run type-check
      - run: npm run lint
      - name: install playwright dependencies
        working-directory: ./packages/e2e
        run: npx playwright install chromium
        if: steps.npm-cache.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: e2e
        working-directory: ./packages/e2e
        run: npm run e2e:headless
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: measure
        working-directory: ./packages/memory
        run: npm run measure
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - run: npm publish --access public
        if: matrix.os == 'ubuntu-24.04'
        working-directory: ./.tmp/dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish GitHub release
        if: matrix.os == 'ubuntu-24.04'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ needs.create-release.outputs.rg_version }}"
          gh release edit $VERSION --draft=false
